import { test, expect } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

test.beforeEach(async ({ request }) => {
  const threads = await (await request.get('/api/v1/threads?limit=100')).json()
  for (const thread of threads.items) await request.delete(`/api/v1/threads/${thread.id}`)
  await request.put('/api/v1/profile', { data: { system_prompt: 'You are Solmu, an autonomous agent.', model: null } })
})

test('Profile shows the saved prompt, saves both fields, and follows live changes without reload controls', async ({ page, request }) => {
  await page.goto('/profile')
  await expect(page.getByLabel('System prompt')).toHaveValue('You are Solmu, an autonomous agent.')
  expect((await (await request.get('/api/v1/threads')).json()).items).toHaveLength(0)
  await expect(page.getByLabel('Profile model')).toHaveValue('')
  await expect(page.getByLabel('Profile model')).toHaveAttribute('placeholder', 'test-model (default)')
  const initial = await (await request.get('/api/v1/profile')).json()
  await expect(page.locator('time')).toHaveAttribute('datetime', initial.edited_at)
  await expect(page.getByRole('button', { name: /reload|refresh/i })).toHaveCount(0)
  await page.getByLabel('System prompt').fill('You are Solmu.\nRespond in Finnish. 🧶')
  await page.getByLabel('Profile model').fill('gpt-6-luna')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('status')).toHaveText('Profile saved')
  const saved = await (await request.get('/api/v1/profile')).json()
  expect(saved).toMatchObject({ system_prompt: 'You are Solmu.\nRespond in Finnish. 🧶', model: 'gpt-6-luna', backend_default_model: 'test-model' })
  expect(saved.edited_at).not.toBe(initial.edited_at)
  await expect(page.locator('time')).toHaveAttribute('datetime', saved.edited_at)
  await expect(page.getByLabel('Profile model')).toHaveAttribute('placeholder', 'test-model (default)')
  if (process.env.SOLMU_CAPTURE_SCREENSHOTS) {
    await mkdir('docs/screenshots', { recursive: true })
    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.locator('.profile-page').evaluate(element => { element.scrollTop = 0 })
    await page.screenshot({ path: 'docs/screenshots/web-profile.png' })
  }
  await request.put('/api/v1/profile', { data: { system_prompt: 'Updated elsewhere', model: null } })
  await expect(page.getByLabel('System prompt')).toHaveValue('Updated elsewhere')
  await expect(page.getByLabel('Profile model')).toHaveValue('')
  await page.getByLabel('System prompt').fill('My unsaved draft')
  await request.put('/api/v1/profile', { data: { system_prompt: 'Another update' } })
  await expect(page.getByRole('status')).toContainText('Your draft is unchanged')
  await expect(page.getByLabel('System prompt')).toHaveValue('My unsaved draft')
  await page.getByRole('button', { name: 'Save profile' }).click()
  await expect(page.getByRole('status')).toHaveText('Profile saved')
  await page.reload()
  await expect(page.getByLabel('System prompt')).toHaveValue('My unsaved draft')
})

test('brand opens Profile above Conversations and new thread clicks reuse the empty thread', async ({ page, request }) => {
  await page.goto('/')
  await expect(page.getByLabel('Message Solmu', { exact: true })).toBeEnabled()
  const initial = page.url()
  for (let index = 0; index < 3; index++) await page.getByRole('button', { name: 'New thread', exact: true }).click()
  await expect(page).toHaveURL(initial)
  expect((await (await request.get('/api/v1/threads')).json()).items).toHaveLength(1)
  await expect(page.getByText('Conversations saved locally', { exact: true })).toHaveCount(0)
  const profile = await page.getByRole('button', { name: 'Profile', exact: true }).boundingBox()
  const conversations = await page.locator('.sidebar-label').boundingBox()
  expect(profile!.y).toBeLessThan(conversations!.y)
  await page.getByRole('button', { name: 'Solmu · Profile' }).click()
  await expect(page).toHaveURL(/\/profile$/)
  await expect(page.getByLabel('System prompt')).toHaveValue('You are Solmu, an autonomous agent.')
  await page.getByLabel('Thread selector').getByRole('button', { name: 'New conversation' }).click()
  await expect(page).toHaveURL(initial)
  await page.getByLabel('Message Solmu', { exact: true }).fill('Hello')
  await page.getByRole('button', { name: 'Send message' }).click()
  await expect(page.getByText('Hello from Solmu', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'New thread', exact: true }).click()
  await expect(page).not.toHaveURL(initial)
  expect((await (await request.get('/api/v1/threads')).json()).items).toHaveLength(2)
})

test('Profile recovers a failed initial fetch automatically', async ({ page }) => {
  let fail = true
  await page.route('**/api/v1/profile', async route => { if (fail) { fail = false; await route.fulfill({ status: 503, json: { error: { message: 'Temporary outage' } } }) } else await route.continue() })
  await page.goto('/profile')
  await expect(page.getByLabel('System prompt')).toHaveValue('You are Solmu, an autonomous agent.')
  await expect(page.getByRole('alert')).toHaveCount(0)
})
