import { test, expect } from '@playwright/test'

test('Tasks creates one-time and cron work, updates live, and keeps the form draft', async ({ page, request }) => {
  await page.goto('/tasks')
  await expect(page.getByRole('heading', { name: 'Tasks', exact: true })).toBeVisible()
  await page.getByLabel('Name').fill('Morning review')
  await page.getByLabel('What should Solmu do?').fill('Summarize the workspace')
  await page.getByLabel('Schedule', { exact: true }).selectOption('cron')
  await page.getByLabel('Cron expression (UTC)').fill('0 9 * * *')
  await page.getByRole('button', { name: 'Create task' }).click()
  const card = page.locator('.task-card').filter({ hasText: 'Morning review' })
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: 'Run history' }).click()
  await expect(card.getByText('No runs yet.')).toBeVisible()
  await card.getByRole('button', { name: 'Pause' }).click()
  await expect(card.getByRole('button', { name: 'Resume' })).toBeVisible()
  await card.getByRole('button', { name: 'Resume' }).click()
  await expect(card.getByRole('button', { name: 'Pause' })).toBeVisible()
  await card.getByRole('button', { name: 'Run now' }).click()
  await expect(card.getByText('completed', { exact: true })).toBeVisible({ timeout: 30_000 })
  await card.getByRole('button', { name: 'Edit' }).click()
  await page.getByLabel('What should Solmu do?').fill('Summarize the project today')
  await page.getByRole('button', { name: 'Save task' }).click()
  await expect(card).toContainText('Summarize the project today')
  await expect(card.getByRole('link', { name: 'Open conversation' })).toHaveAttribute('href', /\/threads\//)
  await page.getByLabel('Name').fill('Keep this draft')
  const external = await request.post('/api/v1/tasks', { data: { name: 'External task', prompt: 'Say hello', schedule_kind: 'cron', schedule: '0 10 * * *' } })
  expect(external.ok()).toBe(true)
  await expect(page.getByRole('heading', { name: 'External task' })).toBeVisible()
  await expect(page.getByLabel('Name')).toHaveValue('Keep this draft')
  if (process.env.SOLMU_CAPTURE_SCREENSHOTS) {
    await page.getByLabel('Name').fill('')
    await page.setViewportSize({ width: 1440, height: 1100 })
    await page.locator('.tasks-page').evaluate(element => { element.scrollTop = 0 })
    await page.screenshot({ path: 'docs/screenshots/web-tasks.png' })
  }
  await card.getByRole('button', { name: 'Delete' }).click()
  await expect(card).toHaveCount(0)
  const externalTask = await external.json()
  await request.delete(`/api/v1/tasks/${externalTask.id}`)
})
