[package]
name = "solmu-boxer-gui"
version = "0.1.4"
edition = "2024"
license.workspace = true

[[bin]]
name = "boxer-gui"
path = "src/main.rs"

[dependencies]
iced = { version = "0.14.0", default-features = false, features = ["tiny-skia", "tokio", "fira-sans", "x11", "wayland"] }
notify = "8.2.0"
serde_json = "1.0.151"
solmu-desktop = { path = "../clients/desktop" }
tokio = { version = "1.49.0", features = ["sync", "time"] }
