import { test, expect } from '@playwright/test'

test('website describes Solmu features and links to every client and installation', async ({ page }) => {
  await page.goto('http://127.0.0.1:4174/solmu/')
  await expect(page).toHaveTitle('Solmu — your ideas, connected')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Good ideas')
  for (const feature of ['See it take shape', 'Follow your threads', 'Bring your model', 'Make it yours', 'Put ideas to work', 'Add project skills']) await expect(page.getByRole('heading', { name: feature })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Use skills' })).toHaveAttribute('href', 'docs/skills/')
  await expect(page.getByRole('link', { name: 'Install individual modules' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Bundle setup' })).toBeVisible()
  await expect(page.getByText(/starts the backend in the background/)).toBeVisible()
  for (const client of ['Terminal', 'Desktop', 'Web']) await expect(page.getByRole('link').filter({ has: page.getByRole('heading', { name: client }) })).toHaveAttribute('href', /github\.com\/panuhorsmalahti\/solmu\/tree\/main\/clients\//)
  await expect(page.getByRole('link', { name: 'Solmu Muxer ↗', exact: true })).toHaveAttribute('href', 'https://github.com/panuhorsmalahti/solmu/tree/main/muxer')
  await expect(page.getByText(/Group real terminal tabs into project spaces/)).toBeVisible()
  await expect(page.getByText(/Keep interactive shells and project commands beside Solmu/)).toBeVisible()
  await expect(page.getByText(/Name your spaces, tabs, and panes; find them with instant search/)).toBeVisible()
  await expect(page.getByText(/Customize colors and shortcuts in Settings; changes apply automatically/)).toBeVisible()
  await expect(page.getByText(/Local automation commands manage layouts, inspect sessions, send terminal input, and read pane screens/)).toBeVisible()
  await expect(page.getByText(/Follow live events or wait for a pane state or matching output/)).toBeVisible()
  await expect(page.getByText(/Queue prompts directly to Solmu, wait for a specific reply, and stop pending work while preserving terminal drafts/)).toBeVisible()
  await expect(page.getByText(/Split panes right or down, drag dividers to resize/)).toBeVisible()
  await expect(page.getByText(/Detach while replies keep running, then reattach/)).toBeVisible()
  await expect(page.getByText(/Layouts and Solmu conversations return after a server restart/)).toBeVisible()
  await expect(page.getByText(/Attach directly to one pane, or stream its screen to scripts with multiple observers and one controller/)).toBeVisible()
  for (const tool of ['Boxer', 'Docker', 'Muxer']) await expect(page.getByRole('heading', { name: tool, exact: true })).toBeVisible()
  expect(await page.getByRole('heading', { level: 3 }).allTextContents()).toEqual(expect.arrayContaining(['Boxer', 'Docker', 'Muxer']))
  expect(await page.locator('.tool-grid > article h3').allTextContents()).toEqual(['Boxer', 'Docker', 'Muxer'])
  await expect(page.locator('pre').filter({ hasText: 'boxer --profile solmu --cwd /path/to/project -- solmu' })).toBeVisible()
  await expect(page.getByText('Launch the backend inside Boxer to protect its tools.', { exact: false })).toBeVisible()
  await expect(page.locator('pre').filter({ hasText: 'docker run --rm --env-file .env -p 127.0.0.1:3000:3000 -v solmu-data:/data ghcr.io/panuhorsmalahti/solmu:latest' })).toBeVisible()
  await expect(page.getByText('Boxer is the recommended agent sandbox.', { exact: false })).toBeVisible()
  for (const script of ['install-bundle.sh', 'install-bundle.ps1']) await expect(page.locator('#install pre').filter({ hasText: `https://raw.githubusercontent.com/panuhorsmalahti/solmu/main/scripts/${script}` })).toBeVisible()
  for (const client of ['cli', 'desktop', 'web', 'muxer']) {
    const image = page.locator(`img[src="screenshots/${client}.png"]`)
    await image.scrollIntoViewIfNeeded()
    await expect(image).toBeVisible()
    await expect.poll(() => image.evaluate((element: HTMLImageElement) => element.complete && element.naturalWidth > 0)).toBe(true)
    expect((await page.request.get(`http://127.0.0.1:4174/solmu/screenshots/${client}.png`)).status()).toBe(200)
  }
  await expect(page.getByRole('link', { name: 'Meet your Solmu' })).toHaveAttribute('href', 'https://github.com/panuhorsmalahti/solmu#install')
  await page.getByRole('link', { name: 'Find your space' }).click()
  await expect(page).toHaveURL(/#your-space$/)
  await expect(page.getByRole('heading', { name: 'Think where you feel at home.' })).toBeInViewport()
})

test('website is usable on a narrow screen and by keyboard', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('http://127.0.0.1:4174/solmu/')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Skip to content' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page).toHaveURL(/#main$/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.getByRole('link', { name: 'GitHub' })).toBeVisible()
})
